### ISSUE TITLE
looks like it isn't making tables in database, is there any way to force make it ?

### ISSUE THREAD

**Issue by yabooo666** [CSSPanel/Panel#1]
✓ Starting...
(node:58) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 ✓ Ready in 386ms
[ERROR] [DB] Error while getting setting: Error: Table 's21_cs_website.sa_mutes' doesn't exist
[ERROR] [DB] Error while getting the admin: Error: Table 's21_cs_website.sa_admins' doesn't exist
[ERROR] [DB] Error while creating sa_admins: Error: Table 's21_cs_website.sa_admins' doesn't exist
[ERROR] [DB] Error while creating tables: Error: Table 's21_cs_website.sa_admins' doesn't exist
[ERROR] [DB] Error while getting all servers: Error: Table 's21_cs_website.sa_servers' doesn't exist
An aria-label or aria-labelledby prop is required for accessibility.
An aria-label or aria-labelledby prop is required for accessibility.
[ERROR] [DB] Error while counting admins: Error: Table 's21_cs_website.sa_servers' doesn't exist
[ERROR] [DB] Error while getting all bans: Error: Table 's21_cs_website.sa_bans' doesn't exist

**Comment by SanjaySRocks** [comment]
getting same error

**Comment by pimpmyname2** [comment]
Use this: https://github.com/CSSPanel/Plugin/blob/main/Database/database_setup.sql
Or install the plugin onto your server instead :D

**Comment by SanjaySRocks** [comment]
Issue is resolved when you install the plugin first
