### ISSUE TITLE
[Feature] Allow external pages to stay in same tab

### ISSUE THREAD

**Issue by mavproductions** [CSSPanel/Panel#4]
Hey!

Just wondering if you could open up the option of external pages in the same tab as a toggle perhaps.

So instead of just this:
`<a href="https://example.com" target="_blank">Link</a>`

perhaps make this available as well
`<a href="https://example.com">Link</a>`

I appreciate the work you've done so far, this is really-really nice. 😀

**Comment by ShiNxz** [comment]
Added :)

**Comment by mavproductions** [comment]
Nice! much better! thank you!!!!
